language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: cbLvVJHTjJfKCkbWYdjfQC7AvN0eIRcMVi9WxFR48c1OwxCLepBm5KWuQzMBoN2Ke/gy2zuouBRSnR7QQ7R0sgzlafqtldVh7+wkoUZIgKGzP3MvPYVKRYqLa2qWtYhhUf21Kkvo47nXkqkD8ebUq/o4RcpmfiWKbuSwjjDiqx2J880sYsN9pHAA3iXOpYwvF0bc+Y/cEwmMlSLqMjoTBd2n/szPFaud9y400TOwn6XICQhMXyZOEPwIwMnyPpX3QtbxTH1FxSlZRrIT51XFzofDyFDZXLKcHxiUeedkT3j9ONr31oc+XcW/f1yaiTasM9scZxfYJF7b6m5y2TkTVGp7YUbkeSPUCMaXkMgxWeF1wcuGK9deyq6GbEv2/nqu+V6lkWtAueZXmXLL25nGn0ocPs/upoY0OHbc5nhBJNNhsE5lEUfbr53n6pmgPjKT7S6SOqBkNFAHKMAy+tAmi1yThpyjccQvJ0hm6zGbmd13zIMyhqXUcCUvU7hqSWt3IeSXa2gp1WvNBTQIbKOKX3RqLFJPeJvwhL/5zV7/ujr4J6c2dRA8sRyqTFrlOLpSd3uiqnYDKNpMhZJ+GjwcgAAyxhItc6ifPdF+9idz+ZL7wKacs0JYvAaOuok0VDeX+VGT0z6lMVPiXNCMrXNCV1VVZoIg43+b/qIVCzZv/Sk=
  app: stark-hamlet-54072
  on:
    repo: ASiede/ourtinerary
