language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: rr0rYfhfhc28hPV8Z9rPn9aG4FgbSpbzxujinMeHi5rTLF3rhATIWGnYjbV3NAathtKuGrXaQRnWKGvgb9NVz8S26CKk67X1PYzsELj9oufaUtz08/wdkyoYQYb90ZZ/PfxwHBkeYUZNNxykz3VEmpyF6kyvRIntDUgZbj1ZY/KJz37qsa3XfNiQoNlLEnOFhi2xBkUXQ0paL23ViBjEhtFzP2l50Vx7N6kX6i3ePIdVyxtqyqNMmXw3a3dlDlr7zzC8TOd83npNoULYA22fS7N4vN4ImgRQWc0rPVRMBlysKSPWNNe3QPZ6ogZ9sLTADsCkaCj29uHEdVuhR7IxD34O+hluQH9VHBmpwwQqjt+6Vhwb3Bne/c6DXMjKqdWr1A8zGbw+Uy2z+nAnqQevSKOAMwn7kOc+umyFNA2tQuqth2tkBFVQKyovIeA0HTUTQku4J7X2xe+V7mqeogAlX3jH5IgmnTnhe4VBvHLtUrVejO303sOcqp/RpkQYKCTLmkNNSUgJv8jFvA1vi9em8/RaKBUnw9PiQFdsh4WHI7mMSSixeAycXfkz3GsOg3nX9nfk/FW58EE2lonnQmNwOPqQzWEh6x63nZ+GNMbtsVQOpbKFRaNWXCJck3gVAZX1NNrN6WLgaoIXfVoYzmVtEJiVIjTmC2MtjT2Mj8E3Q8M=
  app: stark-hamlet-54072
  on:
    repo: ASiede/ourtinerary
