language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: OyJinbaTSwAb7b2cybDUAmyFSOm7jgGHHaMAO3s9QF9lQbrm9AKMfgu4BHleDikrCbi5r6yL6M23VDAMjHBpVL1ilpw9nKsdAteQ4P9k5v2eNMJxCJcULFvci+yh7+0ss+IynPSqm0cyjFoHmgueGozVExn9qzunjKcCWYwlibBVGd2WwwRaeh3IHSNe3X7aKhpLHGZR9oCIQw3zsLrkQs/+rNpXzo914pS/21PHrcovq4t+Qlm7w0hPJDHgCfA7BywCbtvB8vPoQ3ZTL97lTw3Tyaxy6kxjhWLzT6qUJcP6El8iT7vfeloHPgRPozmZbPR0610EuHL2g1uXu9+7wkrSkclHfsHW1WFsTn1nRr6Waij2KsG70uR870vyQrZ4G+zNA+y2tA2xkLoPkj32DJl90u4fCZ0S/+cuIRR4SDp3RknNVNX+4PIHcwc0dx3sY8nyNoMDjKggLYvrj2lM1qvmD4JyMFyxrLGvwA5tY77Ov0lB4/OCL5r/9p8jBeysHSLBbJCl4zxHYaBBhdt01/xUufA7h5zEC4mtI9ANYrDrte46xCR12b3A6XHAjQuXlcGXyhPxRLQyHXG3vtojSTBwOVpoLi/YrkRPo4Lbmt9mqP6NCBxb4JiWFpt24ZqK4LB6zUNtdSfIsxaArgk+CeRB7AeYpZuT+uo+bg8nyao=
  app: stark-hamlet-54072
  on:
    repo: ASiede/ourtinerary
