language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
  matrix:
  - CI=true
  global:
    secure: XiKNg/a5SQu+H2Dw2Hn3rX1seij3Bkg+EecPNhqbZdQYpGqKelAd8q60YIW8rZs3TNbru3Kjl3KMgDgdkonoIw7xzfVh84pjeWfRwDElgm1yY5CcUmcEPiiHumeEoAs3wy7wNh2C/IFX0A7B83z4ay3hTqvCVgd4e4u8qO22pNnHEqiN4du1st2BXXmtm88Hf1j+feUxeDxdQ3LZwScjJDT0X5Vkwz2zUeC2geL1JHOm83oCg3obkTCbqaAuG+mGeKcoJ7NFlI9+Waf1ONBL52SR90F5J8jKtOLX4NmYOVx+5b8nAVf0QbLXjLilk7YhHNHjko5HK3QYBiEWoThp/RxHj/zPtRbw0hU3R3aTkG+b4DXR251A09uh/fZqSlz14DsPBknxzF5hq6h+TSU6yyOS4oU0OWZ7lDioUVZB9QkYBblUYPHwJXwGVm7oVCFNHzJv+2X83AQd3nL4BsHj41+82HmBhfDNM7daRV/h52xUbvsQvyBCsHljKcatREHv1YHQR8ohKMIghB2woFGoU04cOXpHfXP6Thva9GaSRzuHbjRbxlb1GKQGdyOAzfd6HllWtXtWlD4nAXi9hGBZdNAIGt91ZdP5iAtINS9GvCiQVYKlKEAJ96OunAzNMDlPjrqUJfJvJ6bFQhcbaHs3hpaU3iNgSsNdxW3a4h4WYOY=
deploy:
  provider: heroku
  api_key:
    secure: bTHupvTl9gjPUFwbJSNtFB2AYnmLR2fOasgueepGmSpbglRLvlBiQfC7t0MOdwd9v15jdd/PF/ZycRK8WpdmAtcmSWUlgTUWY5TJMph0J7+CGSD7D57tIHYvgw6OqCduqpXNgPJtbYv9IVnZfwZM6g515NlLss3jeCSJAiu1F7Ye9fsa2iPem9qewiEi9VyQORfNL37RjkG7HTT9iySSc5J+iTsU0MGbZjyvgvzOagmZzZiZtMKXkCjfCu/ijrW9n+3maT1ECvse3G2UKj3CQkn0jhHGsVyxpTO9J1nnN3Q8WbOvsgfNstNXDK8gibN7sLeOZhidlqb/5c+5cXDe8lX3BWZZQ/JRsi4wbGI+U9ndVRNM54y2eNCPFCcdLaksEgC2s/W8kigE3JMcRBgjg2wziZCKWAzK3kJ2NaNEFluQEyMWpUGehjRNyESGwzKRsbDThDxSHncMRVwRAPxUDFHiG3LGRFm/QEzaOFolHuBoRgxICDlcy/QdGT0kDzf8ERKIP2llWNJNPEiFRlGDZMH/fWrq3ptIM67Kt2BTS4PDDk0zouoOsXJoABbF2k145esOKrBdF0K2TmSCwxwJbyUQWUVzr6w1MoYs48ET8dsZv0NRdb/LJ3w0drc6xK2PM3iuHzDCDPJBkShKfMuY+iLLP5nb9euR8ox5frb7aCE=
  app: stark-hamlet-54072
  on:
    repo: ASiede/ourtinerary
